version: '3.7'

services:
  app:
    build:
      args:
        user: phpuser
        uid: 1000
      context: ./
      dockerfile: docker-compose/Dockerfile_php8cli_swoole
    image: php8swoole
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 8099:8099
    volumes:
      - ./:/var/www
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
      - ./docker-compose/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:rw,delegated
