version: '3.7'

services:
  app:
    build:
      args:
        user: phpuser
        uid: 1000
      context: ./
      dockerfile: ./docker-compose/Dockerfile_php74
    image: php74dev
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
      - ./docker-compose/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:rw,delegated
    networks:
      - phpnet

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 8099:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - phpnet

networks:
  phpnet:
    driver: bridge
