FROM php:8.0.7-fpm

ARG user
ARG uid

# Install dependencies
RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y \
        build-essential \
        libpng-dev \
        libmcrypt-dev \
        libzip-dev \
        libjpeg62-turbo-dev \
        libfreetype6-dev \
        locales \
        zip unzip \
        jpegoptim optipng pngquant gifsicle \
        vim \
        curl \
        wget \
        procps \
        cron
# Clear cache
#RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo_mysql zip exif pcntl bcmath gd opcache

COPY ./docker-compose/pecl /var/www/html/pecl
RUN cd pecl \
    && echo 'y' | pecl install ./mcrypt-1.0.4.tgz \
    && echo 'extension=mcrypt.so' >  /usr/local/etc/php/conf.d/php-ext-mcrypt.ini \
    && echo "\n\n\n" | pecl install ./redis-5.3.4.tgz \
    && echo 'extension=redis.so' >  /usr/local/etc/php/conf.d/php-ext-redis.ini \
    && echo "\n\n\n\n\n" | pecl install ./swoole-4.6.7.tgz \
    && echo 'extension=swoole.so' >  /usr/local/etc/php/conf.d/php-ext-swoole.ini \
    && cd .. && rm -rf pecl

# 编译方式安装swoole
#RUN wget https://github.com/swoole/swoole-src/archive/refs/tags/v4.6.7.zip \
#    && unzip v4.6.7.zip \
#    && cd swoole-src-4.6.7 \
#    && phpize \
#    && ./configure \
#    && make && make install \
#    && echo 'extension=swoole.so' >  /usr/local/etc/php/conf.d/php-ext-swoole.ini \
#    && cd ../ && rm -rf v4.6.7.zip swoole-src-4.6.7
#    && echo 'extension=redis.so' >  /usr/local/etc/php/conf.d/php-ext-redis.ini


COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/

# Add user for laravel application

RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

WORKDIR /var/www

USER $user

#CMD ["bash", "/var/www/docker/run.sh"]
